# Generated by Django 5.2.6 on 2025-10-01 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_product_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
